title: Random Minecraft (Java Edition)
author: 
  name: Random J. Farmer
  email: random.j.farmer (AT) gmail DOT com

description: >- # this means to ignore newlines until "baseurl:"
  In which our Intrepid Hero retires with his Illgotten Gains
  and Exotic Dancers to a place called Overworld, Mining
  and Building and creating Strange and Wondrous Contraptions
  of Redstone and Slime relying on Obscure and Undocumented
  Behaviours solely found in the One True Java Edition, All
  Other Editions Being Of The Devil!!1
  
baseurl: "/random-minecraft" # the subpath of your site, e.g. /blog
# this needs to be set for minima with disqus
url: "https://random-j-farmer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

disqus:
  shortname: random-minecraft

remote_theme: random-j-farmer/tagged-minima

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    github:  random-j-farmer
    discord:
      name: "Random J Farmer#8197"
      id: 225720541057646592

exclude:
  - julia/
