# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Random Minecraft
author: 
  name: Random J. Farmer
# email: random.j.farmer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Notes on Minecraft (Java Edition)

baseurl: "/random-minecraft" # the subpath of your site, e.g. /blog
# this needs to be set for minima with disqus
url: "https://random-j-farmer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

disqus:
  shortname: random-minecraft

remote_theme: random-j-farmer/tagged-minima

plugins:
  - jekyll-remote-theme

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    github:  random-j-farmer
    